/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef AMMO_COUNTER__H
#define AMMO_COUNTER__H


#define AMMO_COUNTER_BITMAP_WIDTH   128
#define AMMO_COUNTER_BITMAP_HEIGHT  128
#define AMMO_COUNTER_NUM_IMAGES   15


		//	Format:
		//	U,V,Width,Height



const unsigned int ammo_counter_texcoords[] = {
 0, 0, 63, 10,		         // 0 - 
 64, 0, 63, 10,				// 1 -
 0, 16, 63, 10,				// 2 -
 64, 16, 63, 10,				// 3 -
 0, 32, 63, 10,				// 4 -
 64, 32, 63, 10,			   // 5 -
 0, 48, 63, 10,				// 6 -
 64, 48, 63, 10,			   // 7 -
 0, 64, 63, 10,				// 8 -
 64, 64, 63, 10,				// 9 -
 0, 80, 63, 10,				// 10 -
 64, 80, 63, 10,				// 11 -
 0, 96, 63, 10,				// 12 -
 64, 96, 63, 10,				// 13 -
 0, 112, 63, 10,				// 14 -

};


#endif
