/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef PLAYER_CHARACTER__H
#define PLAYER_CHARACTER__H


#define PLAYER_CHARACTER_BITMAP_WIDTH   128
#define PLAYER_CHARACTER_BITMAP_HEIGHT  1024
#define PLAYER_CHARACTER_NUM_IMAGES   22


		//	Format:
		//	U,V,Width,Height



const unsigned int player_character_texcoords[] = {
 0, 30, 29, 34,		      // 0 - idle right
 64, 30, 29, 35,				// 1 -
 0, 94, 29, 35,				// 2 -
 64, 94, 29, 34,				// 3 -
 0, 158, 29, 34,				// 4 -
 64, 158, 29, 34,			   // 5 - idle left
 0, 222, 29, 35,				// 6 -
 64, 222, 29, 35,			   // 7 -
 0, 286, 29, 34,				// 8 -
 64, 286, 29, 34,				// 9 -
 0, 349, 29, 36,				// 10 - run right
 64, 347, 29, 33,				// 11 -
 0, 413, 29, 36,				// 12 -
 64, 412, 29, 36,				// 13 -
 0, 475, 29, 33,				// 14 - 
 64, 477, 29, 36,				// 15 - 
 0, 541, 29, 36,				// 16 - run left
 64, 539, 29, 33,				// 17 -
 0, 605, 29, 36,				// 18 -
 64, 604, 29, 36,				// 19 -
 0, 667, 29, 33,				// 20 -
 64, 669, 29, 36			   // 21 -
};


#endif
