/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef PLAYER_CHARACTER__H
#define PLAYER_CHARACTER__H


#define PLAYER_CHARACTER_BITMAP_WIDTH   128
#define PLAYER_CHARACTER_BITMAP_HEIGHT  1024
#define PLAYER_CHARACTER_NUM_IMAGES   22


		//	Format:
		//	U,V,Width,Height



const unsigned int player_character_texcoords[] = {
 0, 30, 29, 34,		// 0 -
 64, 29, 29, 35,				// 1 -
 0, 93, 29, 35,				// 2 -
 64, 94, 29, 34,				// 3 -
 0, 158, 29, 34,				// 4 -
 64, 158, 29, 34,			   // 5 
 0, 221, 29, 35,				// 6 
 64, 221, 29, 35,			   // 7 
 0, 286, 29, 34,				// 8 
 /*52, 184, 52, 46,				// 9
 52, 184, 52, 46,				// 10
 52, 184, 52, 46,				// 11
 52, 184, 52, 46,				// 12
 52, 184, 52, 46,				// 13
 52, 184, 52, 46,				// 14
 52, 184, 52, 46,				// 15
 52, 184, 52, 46,				// 16
 52, 184, 52, 46,				// 17
 52, 184, 52, 46,				// 18
 52, 184, 52, 46,				// 19
 52, 184, 52, 46,				// 20
 52, 184, 52, 46,				// 21
 52, 184, 52, 46,				// 22*/
};


#endif
