/*======================================================================

   zero coordinates
   Generated by Rel Texture Packer
   relminator 2010

======================================================================*/


#ifndef PLAYER_CHARACTER__H
#define PLAYER_CHARACTER__H


#define PLAYER_CHARACTER_BITMAP_WIDTH   128
#define PLAYER_CHARACTER_BITMAP_HEIGHT  1024
#define PLAYER_CHARACTER_NUM_IMAGES   22


		//	Format:
		//	U,V,Width,Height



const unsigned int player_character_texcoords[] = {
 0, 30, 28, 63,				// 0 -
 64, 29, 92, 63,				// 1 -
 0, 93, 28, 128,				// 2 -
 64, 94, 97, 127,				// 3 -
 0, 92, 52, 46,				// 4
 52, 92, 52, 46,				// 5
 0, 138, 52, 46,				// 6
 0, 184, 52, 46,				// 7
 52, 138, 52, 46,				// 8
 52, 184, 52, 46,				// 9
 52, 184, 52, 46,				// 10
 52, 184, 52, 46,				// 11
 52, 184, 52, 46,				// 12
 52, 184, 52, 46,				// 13
 52, 184, 52, 46,				// 14
 52, 184, 52, 46,				// 15
 52, 184, 52, 46,				// 16
 52, 184, 52, 46,				// 17
 52, 184, 52, 46,				// 18
 52, 184, 52, 46,				// 19
 52, 184, 52, 46,				// 20
 52, 184, 52, 46,				// 21
 52, 184, 52, 46,				// 22
};


#endif
